builds:
  - main: cmd/process-exporter/main.go
    binary: process-exporter
    flags: -tags netgo
    ldflags:
      - -s -w
      - -X github.com/prometheus/common/version.BuildDate={{.Date}}
      - -X github.com/prometheus/common/version.BuildUser=goreleaser
      - -X github.com/prometheus/common/version.Revision={{.FullCommit}}
      - -X main.version={{.Version}}

    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
      - ppc64
      - ppc64le
    goarm:
      - 6
      - 7
archives:
  - name_template: "process-exporter-{{ .Version }}.{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
checksum:
  name_template: checksums.txt
nfpms:
  - homepage: https://github.com/ncabatoff/process-exporter
    maintainer: nick.cabatoff+procexp@gmail.com
    description: Prometheus exporter to report on processes running
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: packaging/process-exporter.service
        dst: /lib/systemd/system/process-exporter.service
      - src: packaging/conf/all.yaml
        dst: /etc/process-exporter/all.yaml
        type: config
      - src: packaging/default/process-exporter
        dst: /etc/default/process-exporter
        type: config

    scripts:
      postinstall: "packaging/scripts/postinstall.sh"
      postremove: "packaging/scripts/postremove.sh"
      preremove: "packaging/scripts/preremove.sh"
release:
  github:
    owner: ncabatoff
    name: process-exporter
  draft: false
  prerelease: true
